/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AffDialog: typeof import('./src/components/dialog/AffDialog.vue')['default']
    BedDialog: typeof import('./src/components/dialog/BedDialog.vue')['default']
    ECharts: typeof import('./src/components/food/ECharts.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FoodDialog: typeof import('./src/components/dialog/FoodDialog.vue')['default']
    LeftMenu: typeof import('./src/components/menu/LeftMenu.vue')['default']
    LocationDialog: typeof import('./src/components/dialog/LocationDialog.vue')['default']
    ManagementDialog: typeof import('./src/components/dialog/ManagementDialog.vue')['default']
    MayPagination: typeof import('./src/components/pagination/MayPagination.vue')['default']
    MayTable: typeof import('./src/components/table/MayTable.vue')['default']
    MayTimePicker: typeof import('./src/components/timepicker/MayTimePicker.vue')['default']
    PriceDialog: typeof import('./src/components/dialog/PriceDialog.vue')['default']
    RoleDialog: typeof import('./src/components/dialog/RoleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupplierDialog: typeof import('./src/components/dialog/SupplierDialog.vue')['default']
    TopMenu: typeof import('./src/components/menu/TopMenu.vue')['default']
  }
}
